artifacts_root: artifacts

data_ingestion:
  data_url: https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
  data_dir: artifacts/data
  train_data_path: artifacts/data/train.csv
  test_data_path: artifacts/data/test.csv
  test_size: 0.2

data_preprocessing:
  max_features: 5000
  vectorizer_path: artifacts/vectorizer/vectorizer.pkl

model_trainer:
  model_path: artifacts/models/bert_model
  batch_size: 8
  max_seq_length: 96
  learning_rate: 2e-5
  epochs: 3

model_evaluation:
  eval_data_dir: "artifacts/data/preprocessed"
  eval_results_dir: "artifacts/evaluation"
  metrics_file: "evaluation_metrics.txt"

model_inference:
  inference_data_dir: "artifacts/data/inference"
  inference_results_dir: "artifacts/inference"
  inference_file: "inference_results.csv"

mlflow:
  tracking_uri: http://127.0.0.1:5000  # Local MLflow server
  experiment_name: SentimentAnalysis